### ISSUE TITLE
Tailwind 1.2?

### ISSUE THREAD

**Issue by mattkoch614** [TVke/react-native-tailwindcss#28]
@TVke  - Does this work with Tailwind 1.2? I am running into a few things when I try this with a tailwind.config.js file generated using 1.2:

- I am trying to use the https://tailwindcss.com/docs/container/#app class but it doesn't look like this library is pulling that in.
- Unless I remove `maxWidth: {}` from the config file, my app errors out: (breakpoints is not a function):

![image](https://user-images.githubusercontent.com/8203609/78929016-9ea82680-7a6f-11ea-99c5-63d68a5fc21f.png)

**Comment by TVke** [comment]
Hi @mattkoch614 

Breakpoints are not supported in ‘react-native-tailwindcss’ as discussed in #25. 
I will release a 1.2 version of this package soon when I see the time but breakpoints are not my priority right now. 

I would accept a PR for this. 

Greetings 
Thomas

**Comment by mattkoch614** [comment]
@TVke - OK, this makes sense. Thank you! For now I will remove this from the tailwind config.
